import {
  lucideArrowRight,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideDisc3,
  lucideExternalLink,
  lucideGlobe,
  lucideLayoutDashboard,
  lucideLibrary,
  lucideListFilter,
  lucideListMusic,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMenu,
  lucideMoon,
  lucideMusic,
  lucidePlus,
  lucideSearch,
  lucideShieldCheck,
  lucideSparkles,
  lucideSun,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUser,
  lucideX,
} from '@ng-icons/lucide';

/** Curated lucide icon set used across the app. Pass to provideIcons(). */
export const APP_ICONS = {
  lucideArrowRight,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideDisc3,
  lucideExternalLink,
  lucideGlobe,
  lucideLayoutDashboard,
  lucideLibrary,
  lucideListFilter,
  lucideListMusic,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMenu,
  lucideMoon,
  lucideMusic,
  lucidePlus,
  lucideSearch,
  lucideShieldCheck,
  lucideSparkles,
  lucideSun,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUser,
  lucideX,
};
