/**
 * AUTO-GENERATED ENVIRONMENT CONFIGURATION
 * 
 * This file is generated by tools/generate-env.js.
 * DO NOT EDIT DIRECTLY.
 * 
 * Variables mapped:
 * - apiUrl
 * - spotifyClientId
 * - spotifyRedirectUri
 */
export const environmentAuto = {
  apiUrl: 'https://clear-songs-api.fly.dev',
  spotifyClientId: '25e740a943ea493d907b6413bd300571',
  spotifyRedirectUri: 'https://clear-songs-web.fly.dev/callback',
};
