/**
 * AUTO-GENERATED ENVIRONMENT CONFIGURATION
 * 
 * This file is generated by tools/generate-env.js.
 * DO NOT EDIT DIRECTLY.
 * 
 * Variables mapped:
 * - apiUrl
 * - spotifyClientId
 * - spotifyRedirectUri
 */
export const environmentAuto = {
  apiUrl: 'http://localhost:3000',
  spotifyClientId: '25e740a943ea493d907b6413bd300571',
  spotifyRedirectUri: 'http://localhost:4200/callback',
};
